server:
  port: 8761 #Eureka ??? ? ???? ???? ??? ?? ?? ???? port

spring:
  application:
    name: discoveryservice # MSA?? ??? ?? ID? name? ??

eureka:
  client: # ?? ? ??? ??? true??. ?? ?? ?, ??? ??? ???? ???? ?? ???? ???? false? ??
    register-with-eureka: false
    fetch-registry: false
